resolver: lts-3.7
packages:
- 'verdict'
- 'verdict-json'
- 'verdict-quickcheck'
- 'verdict-db'
- 'verdict-html'
- location:
    git: https://github.com/jkarni/boolean-normal-forms.git
    commit: 12077171497725fe84e386e209cbfaede89f02d9
extra-deps:
- attoparsec-0.13.0.1
- aeson-0.10.0.0
- markdown-unlit-0.2.0.1
- swagger2-1.2.1
- boolean-normal-forms-0.0.0.1
- http-api-data-0.2.2
flags: {}
extra-package-dbs: []
